fail_fast: true

repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: poetry run isort
        language: system
        types_or: [python, pyi]
      - id: black
        name: black
        entry: poetry run black
        language: system
        types_or: [python, pyi]
      - id: flake8
        name: flake8
        entry: poetry run flake8
        language: system
        types_or: [python, pyi]
      - id: mypy
        name: mypy
        entry: poetry run mypy
        language: system
        types_or: [python, pyi]
